// Generated by CoffeeScript 1.7.1
(function() {
  var Collection, Frozen, Model, Validation, extend,
    __slice = [].slice;

  Validation = (function() {
    function Validation() {}

    Validation.required = function(prop, value, opts, model) {
      var _ref;
      if (value === null || value.trim() === '') {
        return (_ref = opts.message) != null ? _ref : 'Required';
      }
    };

    Validation.coersion = function(prop, value, opts, model) {
      if (value.isValid()) {
        return void 0;
      } else {
        return value.errors;
      }
    };

    return Validation;

  })();

  extend = function() {
    var from, froms, prop, to, value, _i, _len;
    to = arguments[0], froms = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    for (_i = 0, _len = froms.length; _i < _len; _i++) {
      from = froms[_i];
      for (prop in from) {
        value = from[prop];
        if (from.hasOwnProperty(prop)) {
          to[prop] = value;
        }
      }
    }
    return to;
  };

  Model = (function() {
    function Model(attributes) {
      var coersion, error, options, original, prop, type, validation, validator, value, _ref, _ref1;
      if (attributes == null) {
        attributes = {};
      }
      original = attributes;
      _ref = this.coersions;
      for (prop in _ref) {
        coersion = _ref[prop];
        value = attributes[prop];
        if (!(value === void 0 || value instanceof coersion)) {
          if (attributes === original) {
            attributes = extend({}, attributes);
          }
          attributes[prop] = new coersion(value);
        }
      }
      this.attributes = Object.freeze(attributes);
      this.errors = {};
      _ref1 = this.validations;
      for (prop in _ref1) {
        validation = _ref1[prop];
        value = this.attributes[prop];
        if (value === void 0) {
          continue;
        }
        for (type in validation) {
          options = validation[type];
          validator = Validation[type];
          if (validator == null) {
            continue;
          }
          error = validator(prop, value, options, this);
          if (error == null) {
            continue;
          }
          this.errors[prop] = error;
          break;
        }
      }
      Object.freeze(this.errors);
    }

    Model.prototype.get = function(prop) {
      return this.attributes[prop];
    };

    Model.prototype.set = function(prop, value) {
      var attributes;
      attributes = extend({}, this.attributes);
      attributes[prop] = value;
      return new this.constructor(attributes);
    };

    Model.prototype.toJSON = function() {
      var attributes, prop;
      attributes = extend({}, this.attributes);
      for (prop in this.coersions) {
        if (attributes[prop] == null) {
          continue;
        }
        attributes[prop] = attributes[prop].toJSON();
      }
      return attributes;
    };

    Model.prototype.validate = function() {
      var attributes, prop, _ref;
      attributes = extend({}, this.attributes);
      for (prop in this.validations) {
        if (((_ref = this.coersions) != null ? _ref.hasOwnProperty(prop) : void 0) && (attributes[prop] != null)) {
          attributes[prop] = attributes[prop].validate();
        } else {
          if (attributes[prop] == null) {
            attributes[prop] = null;
          }
        }
      }
      return new this.constructor(attributes);
    };

    Model.prototype.isValid = function() {
      return Object.keys(this.errors).length === 0;
    };

    return Model;

  })();

  Collection = (function() {
    Collection.prototype.model = Model;

    function Collection(models) {
      var model;
      if (models == null) {
        models = [];
      }
      if (!(models instanceof Array)) {
        models = [models];
      }
      this.models = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = models.length; _i < _len; _i++) {
          model = models[_i];
          if (model instanceof Model) {
            _results.push(model);
          } else {
            _results.push(new this.model(model));
          }
        }
        return _results;
      }).call(this);
      this.length = this.models.length;
      Object.freeze(this.models);
    }

    Collection.prototype.at = function(key) {
      return this.models[key];
    };

    Collection.prototype.add = function(model) {
      var models;
      if (model == null) {
        model = {};
      }
      if (!(model instanceof Model)) {
        model = new this.model(model);
      }
      models = this.models.concat([model]);
      return new this.constructor(models);
    };

    Collection.prototype.change = function(key, prop, value) {
      var index, model, models;
      models = (function() {
        var _i, _len, _ref, _results;
        _ref = this.models;
        _results = [];
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          model = _ref[index];
          if (index === key) {
            _results.push(model.set(prop, value));
          } else {
            _results.push(model);
          }
        }
        return _results;
      }).call(this);
      return new this.constructor(models);
    };

    Collection.prototype.destroy = function(key) {
      var index, model, models;
      models = (function() {
        var _i, _len, _ref, _results;
        _ref = this.models;
        _results = [];
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          model = _ref[index];
          if (index !== key) {
            _results.push(model);
          }
        }
        return _results;
      }).call(this);
      return new this.constructor(models);
    };

    Collection.prototype.map = function(callback, thisArg) {
      return this.models.map(callback, thisArg);
    };

    Collection.prototype.toJSON = function() {
      var model, _i, _len, _ref, _results;
      _ref = this.models;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        model = _ref[_i];
        _results.push(model.toJSON());
      }
      return _results;
    };

    Collection.prototype.validate = function() {
      var model, models;
      models = (function() {
        var _i, _len, _ref, _results;
        _ref = this.models;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          model = _ref[_i];
          _results.push(model.validate());
        }
        return _results;
      }).call(this);
      return new this.constructor(models);
    };

    Collection.prototype.isValid = function() {
      return this.models.reduce((function(a, e) {
        return a && e.isValid();
      }), true);
    };

    return Collection;

  })();

  Frozen = {
    Model: Model,
    Collection: Collection,
    Validation: Validation
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Frozen;
  } else {
    window.Frozen = Frozen;
  }

}).call(this);
